# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 588)
        self.outputLabel = QtWidgets.QLabel(Dialog)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.clearButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("C"))
        self.clearButton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.shiftButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("<<"))
        self.shiftButton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.shiftButton.setFont(font)
        self.shiftButton.setObjectName("shiftButton")
        self.divButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("/"))
        self.divButton.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divButton.setFont(font)
        self.divButton.setObjectName("divButton")
        self.eightButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.sevenButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.mulButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("*"))
        self.mulButton.setGeometry(QtCore.QRect(275, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.mulButton.setFont(font)
        self.mulButton.setObjectName("mulButton")
        self.fiveButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fourButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.subButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("-"))
        self.subButton.setGeometry(QtCore.QRect(275, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.subButton.setFont(font)
        self.subButton.setObjectName("subButton")
        self.twoButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.oneButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.addButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("+"))
        self.addButton.setGeometry(QtCore.QRect(275, 350, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.zeroButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("."))
        self.decimalButton.setGeometry(QtCore.QRect(190, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.plusminusButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("+/-"))
        self.plusminusButton.setGeometry(QtCore.QRect(10, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.equalButton = QtWidgets.QPushButton(Dialog,clicked= lambda : self.press_it("="))
        self.equalButton.setGeometry(QtCore.QRect(275, 430, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def operation(self,current_str):
        if "/" in current_str:
            for i in range(0,len(current_str)):
                if(current_str[i]=="/"):
                    first=i
                    break
            a=int(current_str[:first])
            b=int(current_str[first+1:])
            ans=round(a/b,3)
            self.outputLabel.setText(str(ans))
        if "*" in current_str:
            for i in range(0,len(current_str)):
                if(current_str[i]=="*"):
                    first=i
                    break
            a=int(current_str[:first])
            b=int(current_str[first+1:])
            ans=a*b
            self.outputLabel.setText(str(ans))
        if "+" in current_str:
            for i in range(0,len(current_str)):
                if(current_str[i]=="+"):
                    first=i
                    break
            a=int(current_str[:first])
            b=int(current_str[first+1:])
            ans=a+b
            self.outputLabel.setText(str(ans))
        if "-" in current_str:
            for i in range(0,len(current_str)):
                if(current_str[i]=="-"):
                    first=i
                    break
            a=int(current_str[:first])
            b=int(current_str[first+1:])
            ans=a-b
            self.outputLabel.setText(str(ans))
    def press_it(self,pressed):
        current_str=self.outputLabel.text()
        if pressed == "C":
            self.outputLabel.setText("0")
        elif(pressed=="<<" and (current_str!="" or current_str!="0")):
                self.outputLabel.setText(current_str[:-1])
        elif(pressed=="+/-"):
            if(current_str[0]=="-"): 
                self.outputLabel.setText(current_str[1:])
            else:
                self.outputLabel.setText("-"+current_str)
        elif(pressed=="="):
            self.operation(current_str=current_str)
        else:
            if current_str=="0":
                self.outputLabel.setText("")
            current_str=self.outputLabel.text()
            if(pressed=="%" and current_str[-1].isdigit()):
                self.outputLabel.setText(current_str+pressed)
            elif(pressed=="/" and current_str[-1].isdigit()):
                self.outputLabel.setText(current_str+pressed)
            elif(pressed=="*" and current_str[-1].isdigit()):
                self.outputLabel.setText(current_str+pressed)
            elif(pressed=="-" and current_str[-1].isdigit()):
                self.outputLabel.setText(current_str+pressed)
            elif(pressed=="+" and current_str[-1].isdigit()):
                self.outputLabel.setText(current_str+pressed)
            
            elif(pressed=="." and ("." not in current_str) and current_str[-1].isdigit()):
                self.outputLabel.setText(current_str+pressed)
            
            elif(pressed>="0" and pressed<="9"):
               self.outputLabel.setText(current_str+pressed)
            
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculator"))
        self.outputLabel.setText(_translate("Dialog", "0"))
        self.percentButton.setText(_translate("Dialog", "%"))
        self.clearButton.setText(_translate("Dialog", "C"))
        self.shiftButton.setText(_translate("Dialog", "<<"))
        self.divButton.setText(_translate("Dialog", "/"))
        self.eightButton.setText(_translate("Dialog", "8"))
        self.nineButton.setText(_translate("Dialog", "9"))
        self.sevenButton.setText(_translate("Dialog", "7"))
        self.mulButton.setText(_translate("Dialog", "x"))
        self.fiveButton.setText(_translate("Dialog", "5"))
        self.sixButton.setText(_translate("Dialog", "6"))
        self.fourButton.setText(_translate("Dialog", "4"))
        self.subButton.setText(_translate("Dialog", "-"))
        self.twoButton.setText(_translate("Dialog", "2"))
        self.threeButton.setText(_translate("Dialog", "3"))
        self.oneButton.setText(_translate("Dialog", "1"))
        self.addButton.setText(_translate("Dialog", "+"))
        self.zeroButton.setText(_translate("Dialog", "0"))
        self.decimalButton.setText(_translate("Dialog", "."))
        self.plusminusButton.setText(_translate("Dialog", "+/-"))
        self.equalButton.setText(_translate("Dialog", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
